ENB.PharmaciesAndPrescriptions.MVC/Models/Prescription/CreateAndEditPrescription.cs
using ENB.PharmaciesAndPrescriptions.Entities;
using ENB.PharmaciesAndPrescriptions.Entities.Collections;
using ENB.PharmaciesAndPrescriptions.MVC.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace ENB.PharmaciesAndPrescriptions.MVC.Models
{
    public class CreateAndEditPrescription :IValidatableObject
    {
        #region "Public Properties"

        public int Id { get; set; }
        public Customer? Customer { get; set; }

        public int CustomerId { get; set; }


        public Physician? Physician { get; set; }

        public int PhysicianId { get; set; }

        public List<SelectListItem>? ListPhysicians { get; set; }

        public List<SelectListItem>? ListCustomers { get; set; }

        public Ref_Prescription_status Prescription_Status { get; set; }

        public string Prescription_Other_details { get; set; } = string.Empty;
        public Ref_payment_method Payment_Method { get; set; }


        [Display(Name = "Presciption issue date")]
        public DateTime Presciption_issue_date { get; set; } = DateTime.Now;


        [Display(Name = "Presciption filled date")]
        public DateTime Presciption_filled_date { get; set; } = DateTime.Now;  

        public DateTime DateCreated { get; set; }


        public DateTime DateModified { get; set; }
        #endregion

        #region validation
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (Prescription_Status==Ref_Prescription_status.None)
            {
                yield return new ValidationResult("Prescription_Status can't be None.", new[] { "Prescription_Status" });
            }

            if (Payment_Method==Ref_payment_method.None)
            {
                yield return new ValidationResult("Payment_Method can't be None.", new[] { "Payment_Method" });
            }
        }
        #endregion
    }
}

ENB.PharmaciesAndPrescriptions.MVC/Models/Prescription/DisplayPrescription.cs
using ENB.PharmaciesAndPrescriptions.Entities;
using ENB.PharmaciesAndPrescriptions.Entities.Collections;
using ENB.PharmaciesAndPrescriptions.MVC.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;


namespace ENB.PharmaciesAndPrescriptions.MVC.Models
{
    public class DisplayPrescription
    {
        #region "Public Properties"

        public int Id { get; set; }
        public Customer? Customer { get; set; }

        public int CustomerId { get; set; }

        
        public Physician? Physician { get; set; }

        public int PhysicianId { get; set; }

       
        public Ref_Prescription_status Prescription_Status { get; set; }

        
        public Ref_payment_method Payment_Method { get; set; }

        
        [Display(Name = "Presciption issue date")]
        public DateTime Presciption_issue_date { get; set; }

        
        [Display(Name = "Presciption filled date")]
        public DateTime Presciption_filled_date { get; set; } 

        public DateTime DateCreated { get ; set ; }

        
        public DateTime DateModified { get ; set ; }

        public string PhysicianName { get; set; } = string.Empty;
        public string CustomerName { get; set; } = string.Empty;

        public string PrescriptionNumber { get; set; } = string.Empty;
        
        #endregion
    }
}

ENB.PharmaciesAndPrescriptions.MVC/Controllers/PrescriptionController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using ENB.PharmaciesAndPrescriptions.Entities.Repositories;
using ENB.PharmaciesAndPrescriptions.Entities;
using ENB.PharmaciesAndPrescriptions.Infrastructure;
using ENB.PharmaciesAndPrescriptions.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using ENB.PharmaciesAndPrescriptions.Entities.Collections;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ENB.PharmaciesAndPrescriptions.MVC.Controllers
{
    public class PrescriptionController : Controller
    {
        private readonly IAsyncCustomerRepository _asyncCustomerRepository;
        private readonly IAsyncPhysicianRepository _asyncPhysicianRepository;
        private readonly IAsyncUnitOfWorkFactory _asyncUnitOfWorkFactory;
        private readonly ILogger<PrescriptionController> _logger;
        private readonly IMapper _mapper;
        private readonly INotyfService _notyf;


        public PrescriptionController(IAsyncCustomerRepository asyncCustomerRepository,
                              IAsyncPhysicianRepository asyncPhysicianRepository,
                           IAsyncUnitOfWorkFactory asyncUnitOfWorkFactory,
                           ILogger<PrescriptionController> logger,
                           IMapper mapper,
                           INotyfService notyf)
        {
            _asyncCustomerRepository = asyncCustomerRepository;
            _asyncPhysicianRepository= asyncPhysicianRepository;
            _asyncUnitOfWorkFactory = asyncUnitOfWorkFactory;
            _logger = logger;
            _mapper = mapper;
            _notyf = notyf;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> List(int CustomerId)
        {
            ViewBag.Idcustm = CustomerId;
            var customer = await _asyncCustomerRepository.FindById(CustomerId);

            ViewBag.Message = customer.FullName;

            return View();
        }


        public async Task<IActionResult> GetPrescriptions(int CustomerId)
        {

            var customer = await _asyncCustomerRepository.FindById(CustomerId, x => x.Prescriptions);

            ViewBag.Message = customer.FullName;

            var Mpdata = new List<DisplayPrescription>();

            _mapper.Map(customer.Prescriptions, Mpdata);

            return Json(new { data = Mpdata });


        }

        [HttpGet]
        public async Task<IActionResult> Create(int CustomerId)
        {
            ViewBag.Idcustm = CustomerId;

            var data = new CreateAndEditPrescription()
            {
               
                ListPhysicians = _asyncPhysicianRepository.FindAll()
                      .Select(d => new SelectListItem
                      {
                          Text = d.FullName,
                          Value = d.Id.ToString(),
                          Selected = true

                      }).Distinct().ToList()

            };

            var customer = await _asyncCustomerRepository.FindById(CustomerId);

            ViewBag.Message = customer.FullName;

            return View(data);
        }

        // POST: LawyerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateAndEditPrescription createAndEditPrescription,
                                                  int CustomerId)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                try
                {
                    await using (await _asyncUnitOfWorkFactory.Create())
                    {
                        var customer = await _asyncCustomerRepository.FindById(CustomerId);
                        
                        Prescription prescription= new();

                        _mapper.Map(createAndEditPrescription, prescription);

                        customer.Prescriptions.Add(prescription);

                        _notyf.Success("Prescription  Added  Successfully! ");

                        return RedirectToAction(nameof(List), new { CustomerId });
                    }
                }
                catch (ModelValidationException mvex)
                {
                    foreach (var error in mvex.ValidationErrors)
                    {
                        ModelState.AddModelError(error.MemberNames.FirstOrDefault() ?? "", error.ErrorMessage!);
                    }
                }
            }
            return View();
        }



        public async Task<IActionResult> Edit(int CustomerId, int id)
        {

            var customer = await _asyncCustomerRepository.FindById(CustomerId);
            ViewBag.Message = customer.FullName;
            ViewBag.Idcustm = CustomerId;
            ViewBag.Id = id;

            var prescriptions = await _asyncCustomerRepository.FindById(CustomerId, x => x.Prescriptions);

            if (prescriptions == null)
            {
                return NotFound();
            }

            var data = new CreateAndEditPrescription()
            {

                ListPhysicians = _asyncPhysicianRepository.FindAll()
                     .Select(d => new SelectListItem
                     {
                         Text = d.FullName,
                         Value = d.Id.ToString(),
                         Selected = true

                     }).Distinct().ToList()

            };

            
                     


            _mapper.Map(customer.Prescriptions.Single(x => x.Id == id), data);

            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CreateAndEditPrescription createAndEditPrescription,
                                            int CustomerId)
        {

            ViewBag.Idcustm = CustomerId;
            if (ModelState.IsValid)
            {
                try
                {
                    await using (await _asyncUnitOfWorkFactory.Create())
                    {

                        var customer = await _asyncCustomerRepository.FindById(CustomerId, x => x.Prescriptions);
                        var prescription = await Task.FromResult(customer.Prescriptions.Single(x => x.Id == createAndEditPrescription.Id));

                        _mapper.Map(createAndEditPrescription, prescription);

                        _notyf.Success("Prescription updated Successfully");

                        return RedirectToAction(nameof(List), new { CustomerId });
                    }
                }
                catch (ModelValidationException mvex)
                {
                    foreach (var error in mvex.ValidationErrors)
                    {
                        ModelState.AddModelError(error.MemberNames.FirstOrDefault() ?? "", error.ErrorMessage!);
                    }
                }
            }
            return View();
        }

        public async Task<IActionResult> Details(int CustomerId, int id)
        {

            var customer = await _asyncCustomerRepository.FindById(CustomerId);

            ViewBag.Idcustm = CustomerId;
            ViewBag.Id = id;           

            var Listprescritions = from p in _asyncCustomerRepository.FindAll().Where(c => c.Id == CustomerId).SelectMany(x => x.Prescriptions)
                          join c in _asyncCustomerRepository.FindAll() on p.CustomerId equals c.Id
                          join ph in _asyncPhysicianRepository.FindAll() on p.PhysicianId equals ph.Id
                          select new DisplayPrescription
                          {
                              Id = p.Id,
                              CustomerId = c.Id,
                              PhysicianName=ph.FullName,
                              CustomerName=c.FullName,
                              PrescriptionNumber=p.PrescriptionNumber,
                              Presciption_issue_date = p.Presciption_issue_date,
                              Presciption_filled_date = p.Presciption_filled_date,
                              Payment_Method = p.Payment_Method,
                              Prescription_Status = p.Prescription_Status,
                              DateCreated= p.DateCreated,
                              DateModified= p.DateModified,
                          };


            if (Listprescritions == null)
            {
                return NotFound();
            }
            var data = new DisplayPrescription();

            var prescription = _mapper.Map(Listprescritions.Single(x => x.Id == id), data);
            ViewBag.Message = prescription.CustomerName;
           
            return View(prescription);
        }


        // GET: ApartmentController/Delete/5
        public async Task<IActionResult> Delete(int CustomerId, int id)
        {
            var customer = await _asyncCustomerRepository.FindById(CustomerId);

            ViewBag.Idcustm = CustomerId;
            ViewBag.Id = id;

            var Listprescritions = from p in _asyncCustomerRepository.FindAll().Where(c => c.Id == CustomerId).SelectMany(x => x.Prescriptions)
                                   join c in _asyncCustomerRepository.FindAll() on p.CustomerId equals c.Id
                                   join ph in _asyncPhysicianRepository.FindAll() on p.PhysicianId equals ph.Id
                                   select new DisplayPrescription
                                   {
                                       Id = p.Id,
                                       CustomerId = c.Id,
                                       PrescriptionNumber = p.PrescriptionNumber,
                                       PhysicianName = ph.FullName,
                                       CustomerName = c.FullName,
                                       Presciption_issue_date = p.Presciption_issue_date,

ENB.PharmaciesAndPrescriptions.MVC/Views/Prescription/Create.cshtml
@model ENB.PharmaciesAndPrescriptions.MVC.Models.CreateAndEditPrescription
@using ENB.PharmaciesAndPrescriptions.Entities;
@{
    ViewData["Title"] = "Create";
}

<div class="alert alert-primary" role="alert">
    <h2>Create New Prescription customer <strong> @ViewBag.Message</strong></h2>
</div>

<div class="row">
    <div class="col-md-12">
        <form asp-action="Create" asp-route-CustomerId="@ViewBag.Idcustm">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="PhysicianId" class="control-label card-header col-md-12" style="margin-bottom:5px"></label>
                        <select id="drpPhysicianList" class="form-control" asp-for="PhysicianId" asp-items="@(new SelectList(Model.ListPhysicians, "Value", "Text"))">
                            <option value="">--Select--</option>
                        </select>
                        <span asp-validation-for="PhysicianId" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Prescription_Status" class="control-label card-header col-md-12" style="margin-bottom:5px"></label>
                        <select asp-for="Prescription_Status" class="form-control" asp-items="Html.GetEnumSelectList<Ref_Prescription_status>()"></select>
                        <span asp-validation-for="Prescription_Status" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Payment_Method" class="control-label card-header col-md-12" style="margin:5px 0 5px"></label>
                        <select asp-for="Payment_Method" class="form-control" asp-items="Html.GetEnumSelectList<Ref_payment_method>()"></select>
                        <span asp-validation-for="Payment_Method" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Presciption_issue_date" class="control-label card-header col-md-12" style="margin:5px 0 5px"></label>
                        <input asp-for="Presciption_issue_date" class="form-control" />
                        <span asp-validation-for="Presciption_issue_date" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">

                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Presciption_filled_date" class="control-label card-header col-md-12" style="margin:5px 0 5px"></label>
                        <input asp-for="Presciption_filled_date" class="form-control" />
                        <span asp-validation-for="Presciption_filled_date" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Prescription_Other_details" class="control-label card-header col-md-12" style="margin:5px 0 5px"></label>
                        <textarea asp-for="Prescription_Other_details" type="text" class="form-control" rows="5" autofocus></textarea>
                        <span asp-validation-for="Prescription_Other_details" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-top:25px">
                <div class="col-md-6">
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <a asp-action="List" asp-route-CustomerId="@ViewBag.Idcustm"  class="btn btn-secondary btn-block col-md-4">Back to List</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

ENB.PharmaciesAndPrescriptions.MVC/Views/Prescription/Delete.cshtml
@using ENB.PharmaciesAndPrescriptions.Entities;
@model ENB.PharmaciesAndPrescriptions.MVC.Models.DisplayPrescription;

@{
    ViewData["Title"] = "Delete";
}


<div class="alert alert-danger" role="alert">
    <h2><strong>Do you really want to remove Prescription: @ViewBag.Message ?</strong></h2>
</div>

<div id="view-all">
    @await Html.PartialAsync("_Details", Model)
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                <a asp-action="List" asp-route-CustomerId="@ViewBag.Idcustm" class="btn btn-secondary btn-block col-md-4">Back to List</a>
                </div>
            </div>
        </div>
}

ENB.PharmaciesAndPrescriptions.MVC/Views/Prescription/Details.cshtml
@using ENB.PharmaciesAndPrescriptions.Entities;
@model ENB.PharmaciesAndPrescriptions.MVC.Models.DisplayPrescription;

@{
    ViewData["Title"] = "Details";
}

<div class="alert alert-primary" role="alert">
    <h2>Details Prescription Customer:<strong> @ViewBag.Message</strong></h2>
</div>

<div id="view-all">
    @await Html.PartialAsync("_Details", Model)
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }
<div class="row">
    <div class="col-md-6">
        <a asp-action="Edit" asp-controller="Prescription" asp-route-CustomerId="@ViewBag.Idcustm" asp-route-id="@ViewBag.Id" class="btn btn-info btn-block col-md-2">Edit</a>
    </div>
    <div class="col-md-6">
        <a asp-action="List" asp-route-CustomerId="@ViewBag.Idcustm" class="btn btn-secondary btn-block col-md-5">Back to List</a>
    </div>
</div>

ENB.PharmaciesAndPrescriptions.MVC/Views/Prescription/Edit.cshtml
@model ENB.PharmaciesAndPrescriptions.MVC.Models.CreateAndEditPrescription
@using ENB.PharmaciesAndPrescriptions.Entities;
@{
    ViewData["Title"] = "Edit";
}

<div class="alert alert-primary" role="alert">
    <h2>Edit Prescription customer <strong> @ViewBag.Message</strong></h2>
</div>

<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit" asp-route-CustomerId="@ViewBag.Idcustm" asp-route-Id="@ViewBag.Id">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="PhysicianId" class="control-label card-header col-md-12" style="margin-bottom:5px"></label>
                        <select id="drpPhysicianList" class="form-control" asp-for="PhysicianId" asp-items="@(new SelectList(Model.ListPhysicians, "Value", "Text"))">
                            <option value="">--Select--</option>
                        </select>
                        <span asp-validation-for="PhysicianId" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Prescription_Status" class="control-label card-header col-md-12" style="margin-bottom:5px"></label>
                        <select asp-for="Prescription_Status" class="form-control" asp-items="Html.GetEnumSelectList<Ref_Prescription_status>()"></select>
                        <span asp-validation-for="Prescription_Status" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Payment_Method" class="control-label card-header col-md-12" style="margin:5px 0 5px"></label>
                        <select asp-for="Payment_Method" class="form-control" asp-items="Html.GetEnumSelectList<Ref_payment_method>()"></select>
                        <span asp-validation-for="Payment_Method" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Presciption_issue_date" class="control-label card-header col-md-12" style="margin:5px 0 5px"></label>
                        <input asp-for="Presciption_issue_date" class="form-control" />
                        <span asp-validation-for="Presciption_issue_date" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">

                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Presciption_filled_date" class="control-label card-header col-md-12" style="margin:5px 0 5px"></label>
                        <input asp-for="Presciption_filled_date" class="form-control" />
                        <span asp-validation-for="Presciption_filled_date" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Prescription_Other_details" class="control-label card-header col-md-12" style="margin:5px 0 5px"></label>
                        <textarea asp-for="Prescription_Other_details" type="text" class="form-control" rows="5" autofocus></textarea>
                        <span asp-validation-for="Prescription_Other_details" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-top:25px">
                <div class="col-md-6">
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <a asp-action="List" asp-route-CustomerId="@ViewBag.Idcustm" class="btn btn-secondary btn-block col-md-4">Back to List</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

ENB.PharmaciesAndPrescriptions.MVC/Views/Prescription/List.cshtml
@using ENB.PharmaciesAndPrescriptions.Entities;
@model IEnumerable<ENB.PharmaciesAndPrescriptions.MVC.Models.DisplayPrescription>
@{
    ViewData["Title"] = "List";

}

<div class="alert alert-primary" role="alert">
    <h2>Prescriptions customer : <strong> @ViewBag.Message </strong></h2>
</div>
<a asp-action="Create" id="adddrug_medication" asp-controller="Prescription" asp-route-CustomerId="@ViewBag.Idcustm" class="btn btn-success text-white" style="margin-bottom:10px"><i class="fas fa-prescription"></i> New Prescription</a>
<table id="PrescriptionTable" class="table table-striped table-bordered" width="100%">
    <thead>
        <tr>
            <th>Id</th>
            <th>pres.Number</th>
            <th>Status Pres.</th>
            <th>Payment M.</th>
            <th>Issue date</th>
            <th>Filled date</th>
            <th> </th>
        </tr>
    </thead>
</table>

<link href="~/lib/datatable/datatables-1.12.1/css/datatables.bootstrap5.min.css" rel="stylesheet" />

@section scripts{
    <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="~/lib/datatable/datatables-1.12.1/js/jquery.datatables.min.js"></script>
    <script src="~/lib/datatable/datatables-1.12.1/js/datatables.bootstrap5.min.js"></script>
    <script>
        var Popup, datatable, Idcustm = parseInt('@ViewBag.Idcustm'), IdWard = parseInt('@ViewBag.Ward_Id')
        $(document).ready(function () {
            datatable = $("#PrescriptionTable").DataTable({
                "ajax": {
                    "url": "/Prescription/GetPrescriptions/?CustomerId=" + Idcustm + "",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [

                    { "data": "id" },
                    {
                        "data": "prescriptionNumber",
                        "width": "50px",
                        "render": function (data, type, row, meta) {
                            return '<b><a href="/Prescription/Details/?id=' + row.id + "&CustomerId=" + Idcustm + '">' + data + '</b></a>';
                        }
                    },
                    {
                        "data": "prescription_Status",
                        "render": Refprescription_Status

                    },
                    { "data": "payment_Method", "render": RefpaymentMethode },
                    { "data": "presciption_issue_date", "render": dateFormatter },
                    { "data": "presciption_filled_date", "render": dateFormatter },
                    {
                        "data": "id", "render": function (data) {
                            return "<a class= 'btn btn-primary btn-sm text-white' onclick=location.href='@Url.Action("Edit","Prescription")?id=" + data + "&CustomerId=" + Idcustm + "'><i class='fas fa-pencil'></i><b> Edit</b></a>" + "\r\n" +
                                "<a class= 'btn btn-danger btn-sm text-white' style = 'margin-left:5px' onclick =location.href='@Url.Action("Delete","Prescription")?id=" + data + "&CustomerId=" + Idcustm + "'> <i class='fa-solid fa-trash-can' > </i><b> Delete</b > </a> " + "\r\n" +
                                "<a class= 'btn btn-info btn-sm' style='margin-left:5px' onclick=location.href='@Url.Action("List", "PrescriptionItems")?PrescriptionId=" + data + "&CustomerId=" + Idcustm + "'><i class='far fa-building'></i><b> Prescription Items</b> </a>" ;
                        },
                        "orderable": false,
                        "searchable": false,
                        "width": "350px"
                    }

                ],
                "language": {

                    "emptyTable": "No data Found, Please Click On <b>Add New</b> Button"
                }

            });

        });




        console.log(Idcustm);


        function dateFormatter(data) {
            var dateAsString = data;

            var yearNumber = dateAsString.substring(0, 4);
            var monthNumber = dateAsString.substring(5, 7);
            var dayNumber = dateAsString.substring(8, 10);
            var dat = dayNumber + "/" + monthNumber + "/" + yearNumber;
            return dat;
        }

        function RefpaymentMethode(data) {
            var typgen;
            switch (data) {
                case 1:
                    typgen = "Filled"
                    break;
                case 2:
                    typgen = "Part Filled"
                    break;                        
                case 3:
                    typgen = "Filled but not collected"
                    break;
                default:
                // code block
            }
            return typgen
        }

        function Refprescription_Status(data) {
            var typgen;
            switch (data) {
                case 1:
                    typgen = "Cash"
                    break;
                case 2:
                    typgen = "Credit card"
                    break;
                default:
                // code block
            }
            return typgen
        }

    </script>
    }