ENB.PharmaciesAndPrescriptions.MVC/Models/PrescriptionItems/CreateAndEditPrescriptionItem.cs
using ENB.PharmaciesAndPrescriptions.Entities;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace ENB.PharmaciesAndPrescriptions.MVC.Models
{
    public class CreateAndEditPrescriptionItem: IValidatableObject
    {
        public int Id { get; set; }
        public Prescription? Prescription { get; set; }

        public int PrescriptionId { get; set; }

        public Drug_medication? Drug_medication { get; set; }

        public int Drug_medicationId { get; set; }

        public Customer? Customer { get; set; }

        public int CustomerId { get; set; }

        public int prescription_quantity { get; set; }

        public string Instructions_to_customer { get; set; } = String.Empty;

        public DateTime DateCreated { get; set; }

        public DateTime DateModified { get; set; }

        public List<SelectListItem>? ListDrugs { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (string.IsNullOrEmpty(Instructions_to_customer))
            {
                yield return new ValidationResult("Instructions to customer can't be None.", new[] { "Instructions_to_customer" });
            }
        }
    }
}

ENB.PharmaciesAndPrescriptions.MVC/Models/PrescriptionItems/DisplayPrescriptionItem.cs
using ENB.PharmaciesAndPrescriptions.Entities;

namespace ENB.PharmaciesAndPrescriptions.MVC.Models
{
    public class DisplayPrescriptionItem
    {
        public int Id { get; set; }
        public Prescription? Prescription { get; set; }

        public int PrescriptionId { get; set; }

        public Drug_medication? Drug_medication { get; set; }
        
        public int Drug_medicationId { get; set; }

        public Customer? Customer { get; set; }

        public int CustomerId { get; set; }


        public int Prescription_quantity { get; set; }
        
        public string Instructions_to_customer { get; set; } = String.Empty;

        public string NameCustomer { get; set; }= String.Empty; 

        public string NamePhysician { get; set; }=String.Empty;

        public string NumberPrescription { get; set; } = String.Empty;

        public string DrugName { get; set; } = string.Empty;

        public DateTime DateCreated { get; set; }
       
        public DateTime DateModified { get; set; }
    }
}

ENB.PharmaciesAndPrescriptions.MVC/Controllers/PrescriptionItemsController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using ENB.PharmaciesAndPrescriptions.EF.Migrations;
using ENB.PharmaciesAndPrescriptions.Entities;
using ENB.PharmaciesAndPrescriptions.Entities.Collections;
using ENB.PharmaciesAndPrescriptions.Entities.Repositories;
using ENB.PharmaciesAndPrescriptions.Infrastructure;
using ENB.PharmaciesAndPrescriptions.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ENB.PharmaciesAndPrescriptions.MVC.Controllers
{
    public class PrescriptionItemsController : Controller
    {
        private readonly IAsyncCustomerRepository _asyncCustomerRepository;
        private readonly IAsyncDrugCompanyRepository _asyncDrugCompanyRepository ;
        private readonly IAsyncPhysicianRepository _asyncPhysicianRepository;
        private readonly IAsyncUnitOfWorkFactory _asyncUnitOfWorkFactory;
        private readonly ILogger<PrescriptionItemsController> _logger;
        private readonly INotyfService _notyfService;
        private readonly IMapper _imapper;
        public PrescriptionItemsController(IAsyncCustomerRepository asyncCustomerRepository, 
                                            IAsyncDrugCompanyRepository asyncDrugCompanyRepository,
                                            IAsyncPhysicianRepository asyncPhysicianRepository,
                                            IAsyncUnitOfWorkFactory asyncUnitOfWorkFactory,
                                            ILogger<PrescriptionItemsController> logger,
                                            INotyfService notyfService,
                                            IMapper imapper)
        {
            _asyncCustomerRepository = asyncCustomerRepository;
            _asyncDrugCompanyRepository = asyncDrugCompanyRepository;
            _asyncPhysicianRepository= asyncPhysicianRepository;
            _asyncUnitOfWorkFactory = asyncUnitOfWorkFactory;
            _logger = logger;
            _notyfService= notyfService;
            _imapper = imapper;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> List(int CustomerId,int PrescriptionId)
        {
            ViewBag.Idcustm = CustomerId;
            ViewBag.presId = PrescriptionId;

            var customer = await _asyncCustomerRepository.FindById(CustomerId, prs => prs.Prescriptions);
            var prescription = customer.Prescriptions.Single(x => x.Id == PrescriptionId);

            ViewBag.Message = customer.FullName;
            ViewBag.presNumber = prescription.PrescriptionNumber;

            return View();
        }


        public async Task<IActionResult> GetPrescriptionsItems(int customerId, int PrescriptionId)
        {
            

            var presItems = (from prsit in _asyncCustomerRepository.FindAll().Where(cs => cs.Id == customerId).SelectMany(presIt => presIt.Prescription_Items)
                                   .Where(x => x.PrescriptionId == PrescriptionId)
                            join prs in _asyncCustomerRepository.FindAll().Where(cst => cst.Id == customerId).SelectMany(pres => pres.Prescriptions)
                                on prsit.PrescriptionId equals prs.Id
                            join cst in _asyncCustomerRepository.FindAll() on prs.CustomerId equals cst.Id
                            join phy in _asyncPhysicianRepository.FindAll() on prs.PhysicianId equals phy.Id
                            join drgm in _asyncDrugCompanyRepository.FindAll().SelectMany(z => z.Drug_Medications)
                                  on prsit.Drug_medicationId equals drgm.Id

                            select new DisplayPrescriptionItem
                          {
                              Id = prsit.Id,
                              Prescription_quantity = prsit.prescription_quantity,
                              Instructions_to_customer=prsit.Instructions_to_customer,
                              NameCustomer = cst.FullName,
                              NamePhysician = phy.FullName,
                              NumberPrescription = prs.PrescriptionNumber,
                              DrugName = drgm.Drug_name,
                              DateCreated=prsit.DateCreated,
                              DateModified=prsit.DateModified,

                            }).ToList();




            var Mpdata = new List<DisplayPrescriptionItem>();

            var lst = await Task.FromResult(presItems);

            _imapper.Map(lst, Mpdata);

            return Json(new { data = Mpdata });


        }

        [HttpGet]
        public async Task<IActionResult> Create(int CustomerId, int PrescriptionId)
        {
            ViewBag.Idcustm = CustomerId;
            ViewBag.presId = PrescriptionId;    
            
            var data = new CreateAndEditPrescriptionItem()
            {
                
                ListDrugs =  _asyncDrugCompanyRepository.FindAll()
                          .SelectMany(x => x.Drug_Medications)
                      .Select(d => new SelectListItem
                      {
                          Text = d.Drug_name,
                          Value = d.Id.ToString(),
                          Selected = true

                      }).Distinct().ToList()

            };

            var customer = await _asyncCustomerRepository.FindById(CustomerId);


            ViewBag.Message = customer.FullName;

            return View(data);
        }

        // POST: LawyerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateAndEditPrescriptionItem createAndEditPrescriptionItem, 
                                                    int CustomerId, 
                                                    int PrescriptionId)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                try
                {
                    await using (await _asyncUnitOfWorkFactory.Create())
                    {
                        var customer = await _asyncCustomerRepository.FindById(CustomerId, x => x.Prescriptions);

                        var prescr = customer.Prescriptions.Single(x => x.Id == PrescriptionId);

                        Prescription_item prescription_Item   = new ();

                        _imapper.Map(createAndEditPrescriptionItem, prescription_Item);
                       
                        prescr.Prescription_Items.Add(prescription_Item);

                          _notyfService.Success("PrescriptionItem Added  Successfully! ");

                        return RedirectToAction(nameof(List), new { CustomerId, PrescriptionId });
                    }
                }
                catch (ModelValidationException mvex)
                {
                    foreach (var error in mvex.ValidationErrors)
                    {
                        ModelState.AddModelError(error.MemberNames.FirstOrDefault() ?? "", error.ErrorMessage!);
                    }
                }
            }
            return View();
        }



        public async Task<IActionResult> Edit(int CustomerId,
                                                    int PrescriptionId, int id)
        {

            var customer = await _asyncCustomerRepository.FindById(CustomerId, x => x.Prescription_Items);
            var prescr = customer.Prescription_Items.Where(x => x.PrescriptionId == PrescriptionId)
                       .Single(y => y.Id == id);
            ViewBag.Message = customer.FullName;
            ViewBag.Idcustm = CustomerId;
            ViewBag.presId = PrescriptionId;
            ViewBag.Id = id;
            


            if (customer == null)
            {
                return NotFound();
            }



            var data = new CreateAndEditPrescriptionItem()
            {

                ListDrugs = _asyncDrugCompanyRepository.FindAll()
                         .SelectMany(x => x.Drug_Medications)
                     .Select(d => new SelectListItem
                     {
                         Text = d.Drug_name,
                         Value = d.Id.ToString(),
                         Selected = true

                     }).Distinct().ToList()

            };

            _imapper.Map(prescr, data);

            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CreateAndEditPrescriptionItem createAndEditPrescriptionItem, int CustomerId,
                                                    int PrescriptionId)
        {

            ViewBag.Idcustm = CustomerId;
            if (ModelState.IsValid)
            {
                try
                {
                    await using (await _asyncUnitOfWorkFactory.Create())
                    {

                        var customer = await _asyncCustomerRepository.FindById(CustomerId, x => x.Prescription_Items);
                        var presItem = customer.Prescription_Items.Where(x => x.PrescriptionId == PrescriptionId)
                                   .Single(y => y.Id == createAndEditPrescriptionItem.Id);

                        _imapper.Map(createAndEditPrescriptionItem, presItem);

                         _notyfService.Success("PrescriptionItem updated Successfully");

                        return RedirectToAction(nameof(List), new { CustomerId, PrescriptionId });
                    }
                }
                catch (ModelValidationException mvex)
                {
                    foreach (var error in mvex.ValidationErrors)
                    {
                        ModelState.AddModelError(error.MemberNames.FirstOrDefault() ?? "", error.ErrorMessage!);
                    }
                }
            }
            return View();
        }

ENB.PharmaciesAndPrescriptions.MVC/Views/PrescriptionItems/Create.cshtml
@model ENB.PharmaciesAndPrescriptions.MVC.Models.CreateAndEditPrescriptionItem

@{
    ViewData["Title"] = "Create";
}

<div class="alert alert-primary" role="alert">
    <h2>Create New PrescriptionItem customer <strong> @ViewBag.Message</strong></h2>
</div>

<div class="row">
    <div class="col-md-12">
        <form asp-action="Create" asp-route-CustomerId="@ViewBag.Idcustm" asp-route-PrescriptionId="@ViewBag.presId">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Drug_medicationId" class="control-label card-header col-md-12" style="margin-bottom:5px"></label>
                        <select id="Drug_medicationList" class="form-control" asp-for="Drug_medicationId" asp-items="@(new SelectList(Model.ListDrugs, "Value", "Text"))">
                            <option value="">--Select--</option>
                        </select>
                        <span asp-validation-for="Drug_medicationId" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="prescription_quantity" class="control-label card-header col-md-12" style="margin-bottom:5px"></label>
                        <input asp-for="prescription_quantity" class="form-control" />
                        <span asp-validation-for="prescription_quantity" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Instructions_to_customer" class="control-label card-header col-md-12" style="margin:5px 0 5px"></label>
                        <textarea asp-for="Instructions_to_customer" type="text" class="form-control" rows="5" autofocus></textarea>
                        <span asp-validation-for="Instructions_to_customer" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-top:25px">
                <div class="col-md-6">
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <a asp-action="List" asp-route-CustomerId="@ViewBag.Idcustm" asp-route-PrescriptionId="@ViewBag.presId" class="btn btn-secondary btn-block col-md-4">Back to List</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

ENB.PharmaciesAndPrescriptions.MVC/Views/PrescriptionItems/Delete.cshtml
@using ENB.PharmaciesAndPrescriptions.Entities;
@model ENB.PharmaciesAndPrescriptions.MVC.Models.DisplayPrescriptionItem;

@{
    ViewData["Title"] = "Delete";
}


<div class="alert alert-danger" role="alert">
    <h2><strong>Do you really want to remove this PrescriptionItem: @ViewBag.Message ?</strong></h2>
</div>

<div id="view-all">
    @await Html.PartialAsync("_Details", Model)
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <a asp-action="List" asp-route-CustomerId="@ViewBag.Idcustm" asp-route-PrescriptionId="@ViewBag.presId" class="btn btn-secondary btn-block col-md-4">Back to List</a>
            </div>
        </div>
    </div>
}

ENB.PharmaciesAndPrescriptions.MVC/Views/PrescriptionItems/Details.cshtml
@using ENB.PharmaciesAndPrescriptions.Entities;
@model ENB.PharmaciesAndPrescriptions.MVC.Models.DisplayPrescriptionItem;

@{
    ViewData["Title"] = "Details";
}

<div class="alert alert-primary" role="alert">
    <h2>Details PrescriptionItem Drug:<strong> @ViewBag.Message</strong></h2>
</div>

<div id="view-all">
    @await Html.PartialAsync("_Details", Model)
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }
<div class="row">
    <div class="col-md-6">
        <a asp-action="Edit" asp-controller="PrescriptionItems" asp-route-CustomerId="@ViewBag.Idcustm" asp-route-PrescriptionId="@ViewBag.presId" asp-route-id="@ViewBag.Id" class="btn btn-info btn-block col-md-2">Edit</a>
    </div>
    <div class="col-md-6">
        <a asp-action="List" asp-route-CustomerId="@ViewBag.Idcustm" asp-route-PrescriptionId="@ViewBag.presId" class="btn btn-secondary btn-block col-md-5">Back to List</a>
    </div>
</div>

ENB.PharmaciesAndPrescriptions.MVC/Views/PrescriptionItems/Edit.cshtml
@model ENB.PharmaciesAndPrescriptions.MVC.Models.CreateAndEditPrescriptionItem

@{
    ViewData["Title"] = "Edit";
}

<div class="alert alert-primary" role="alert">
    <h2>Edit PrescriptionItem customer <strong> @ViewBag.Message</strong></h2>
</div>

<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit" asp-route-CustomerId="@ViewBag.Idcustm" asp-route-PrescriptionId="@ViewBag.presId" asp-route-Id="@ViewBag.Id">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Drug_medicationId" class="control-label card-header col-md-12" style="margin-bottom:5px"></label>
                        <select id="Drug_medicationList" class="form-control" asp-for="Drug_medicationId" asp-items="@(new SelectList(Model.ListDrugs, "Value", "Text"))">
                            <option value="">--Select--</option>
                        </select>
                        <span asp-validation-for="Drug_medicationId" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="prescription_quantity" class="control-label card-header col-md-12" style="margin-bottom:5px"></label>
                        <input asp-for="prescription_quantity" class="form-control" />
                        <span asp-validation-for="prescription_quantity" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Instructions_to_customer" class="control-label card-header col-md-12" style="margin:5px 0 5px"></label>
                        <textarea asp-for="Instructions_to_customer" type="text" class="form-control" rows="5" autofocus></textarea>
                        <span asp-validation-for="Instructions_to_customer" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-top:25px">
                <div class="col-md-6">
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <a asp-action="List" asp-route-CustomerId="@ViewBag.Idcustm" asp-route-PrescriptionId="@ViewBag.presId" class="btn btn-secondary btn-block col-md-4">Back to List</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

ENB.PharmaciesAndPrescriptions.MVC/Views/PrescriptionItems/List.cshtml
@using ENB.PharmaciesAndPrescriptions.Entities;
@model IEnumerable<ENB.PharmaciesAndPrescriptions.MVC.Models.DisplayPrescriptionItem>
@{
    ViewData["Title"] = "List";

}

<div class="alert alert-primary" role="alert">
    <h2>Prescription Items customer : <strong> @ViewBag.Message </strong></h2>
</div>
<a asp-action="Create" id="adddrug_medication" asp-controller="PrescriptionItems" asp-route-CustomerId="@ViewBag.Idcustm" asp-route-PrescriptionId="@ViewBag.presId" class="btn btn-success text-white" style="margin-bottom:10px"><i class="fas fa-prescription"></i> New Prescription Item</a>
<table id="PrescriptionItemsTable" class="table table-striped table-bordered" width="100%">
    <thead>
        <tr>
            <th>Id</th>
            <th>drugName</th>
            <th>Quantity</th>
            <th>Name Customer</th>
            <th>Name Physician</th>
            <th>N° Prescription</th>
            <th> </th>
        </tr>
    </thead>
</table>

<link href="~/lib/datatable/datatables-1.12.1/css/datatables.bootstrap5.min.css" rel="stylesheet" />

@section scripts{
    <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="~/lib/datatable/datatables-1.12.1/js/jquery.datatables.min.js"></script>
    <script src="~/lib/datatable/datatables-1.12.1/js/datatables.bootstrap5.min.js"></script>
    <script>
        var Popup, datatable, Idcustm = parseInt('@ViewBag.Idcustm'), IdPres = parseInt('@ViewBag.presId')
        $(document).ready(function () {
            datatable = $("#PrescriptionItemsTable").DataTable({
                "ajax": {
                    "url": "/PrescriptionItems/GetPrescriptionsItems/?CustomerId=" + Idcustm + "&PrescriptionId=" + IdPres + "",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [

                    { "data": "id" },
                    {
                        "data": "drugName",
                        "width": "150px",
                        "render": function (data, type, row, meta) {
                            return '<b><a href="/PrescriptionItems/Details/?id=' + row.id + "&CustomerId=" + Idcustm + "&PrescriptionId=" + IdPres +  '">' + data + '</b></a>';
                        }
                    },
                    { "data": "prescription_quantity"},
                    { "data": "nameCustomer" },
                    { "data": "namePhysician" },
                    { "data": "numberPrescription"},
                    {
                        "data": "id", "render": function (data) {
                            return "<a class= 'btn btn-primary btn-sm text-white' onclick=location.href='@Url.Action("Edit","PrescriptionItems")?id=" + data + "&CustomerId=" + Idcustm + "&PrescriptionId=" + IdPres + "'><i class='fas fa-pencil'></i><b> Edit</b></a>" + "\r\n" +
                                "<a class= 'btn btn-danger btn-sm text-white' style = 'margin-left:5px' onclick =location.href='@Url.Action("Delete","PrescriptionItems")?id=" + data + "&CustomerId=" + Idcustm + "&PrescriptionId=" + IdPres + "'> <i class='fa-solid fa-trash-can' > </i><b> Delete</b > </a> ";
                        },
                        "orderable": false,
                        "searchable": false,
                        "width": "150px"
                    }

                ],
                "language": {

                    "emptyTable": "No data Found, Please Click On <b>Add New</b> Button"
                }

            });

        });




        console.log(Idcustm);


        //function dateFormatter(data) {
        //    var dateAsString = data;

        //    var yearNumber = dateAsString.substring(0, 4);
        //    var monthNumber = dateAsString.substring(5, 7);
        //    var dayNumber = dateAsString.substring(8, 10);
        //    var dat = dayNumber + "/" + monthNumber + "/" + yearNumber;
        //    return dat;
        //}

        //function RefpaymentMethode(data) {
        //    var typgen;
        //    switch (data) {
        //        case 1:
        //            typgen = "Filled"
        //            break;
        //        case 2:
        //            typgen = "Part Filled"
        //            break;
        //        case 3:
        //            typgen = "Filled but not collected"
        //            break;
        //        default:
        //        // code block
        //    }
        //    return typgen
        //}

        //function Refprescription_Status(data) {
        //    var typgen;
        //    switch (data) {
        //        case 1:
        //            typgen = "Cash"
        //            break;
        //        case 2:
        //            typgen = "Credit card"
        //            break;
        //        default:
        //        // code block
        //    }
        //    return typgen
        //}

    </script>
    }

ENB.PharmaciesAndPrescriptions.MVC/Views/PrescriptionItems/_Details.cshtml
@model ENB.PharmaciesAndPrescriptions.MVC.Models.DisplayPrescriptionItem

<div>
   
    <dl class="row">        
        <dt class="col-sm-2 card-header" style="margin-top:5px">
            @Html.DisplayNameFor(model => model.Prescription_quantity)
        </dt>
        <dd class="col-sm-10 card-header" style="margin-top:5px">
            @Html.DisplayFor(model => model.Prescription_quantity)
        </dd>
        <dt class="col-sm-2 card-header" style="margin-top:5px">
            @Html.DisplayNameFor(model => model.Instructions_to_customer)
        </dt>
        <dd class="col-sm-10 card-header" style="margin-top:5px">
            @Html.DisplayFor(model => model.Instructions_to_customer)
        </dd>
        <dt class="col-sm-2 card-header" style="margin-top:5px">
            @Html.DisplayNameFor(model => model.NameCustomer)
        </dt>
        <dd class="col-sm-10 card-header" style="margin-top:5px">
            @Html.DisplayFor(model => model.NameCustomer)
        </dd>
        <dt class="col-sm-2 card-header" style="margin-top:5px">
            @Html.DisplayNameFor(model => model.NamePhysician)
        </dt>
        <dd class="col-sm-10 card-header" style="margin-top:5px">
            @Html.DisplayFor(model => model.NamePhysician)
        </dd>
        <dt class="col-sm-2 card-header" style="margin-top:5px">
            @Html.DisplayNameFor(model => model.NumberPrescription)
        </dt>
        <dd class="col-sm-10 card-header" style="margin-top:5px">
            @Html.DisplayFor(model => model.NumberPrescription)
        </dd>
        <dt class="col-sm-2 card-header" style="margin-top:5px">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class="col-sm-10 card-header" style="margin-top:5px">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class="col-sm-2 card-header" style="margin-top:5px">
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>
        <dd class="col-sm-10 card-header" style="margin-top:5px">
            @Html.DisplayFor(model => model.DateModified)
        </dd>
    </dl>
</div>