ENB.PharmaciesAndPrescriptions.MVC/Models/Drug_Medication/CreateAndEditDrugAndMedication.cs
using ENB.PharmaciesAndPrescriptions.Entities.Collections;
using ENB.PharmaciesAndPrescriptions.Entities;
using System.ComponentModel.DataAnnotations;

namespace ENB.PharmaciesAndPrescriptions.MVC.Models
{
    public class CreateAndEditDrugAndMedication : IValidatableObject
    {
        public int Id { get; set; }
        public string Drug_name { get; set; } = String.Empty;
        public Drug_company? Drug_Company { get; set; }
        public int Drug_companyId { get; set; }
        public decimal Drug_cost { get; set; }
        public DateTime Drug_available_date { get; set; }
        public DateTime Drug_Withdrawn_date { get; set; }
        public string Drug_description { get; set; } = String.Empty;
        public Drug_generic Drug_generic { get; set; }
        public string Generic_equivalent_generic_id { get; set; } = String.Empty;
        public string Other_drug_details { get; set; } = String.Empty;
        public Prescription_Items? Prescription_Items { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateModified { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if(Drug_generic==Drug_generic.None)
            {
                yield return new ValidationResult("Drug_generic can't be None", new[] { "Drug_generic" });
            }
        }
    }
}

ENB.PharmaciesAndPrescriptions.MVC/Models/Drug_Medication/DisplayDrugAndMedication.cs
using ENB.PharmaciesAndPrescriptions.Entities.Collections;
using ENB.PharmaciesAndPrescriptions.Entities;

namespace ENB.PharmaciesAndPrescriptions.MVC.Models
{
    public class DisplayDrugAndMedication
    {
        public int Id { get; set; }
        public string Drug_name { get; set; } = String.Empty;
        public Drug_company? Drug_Company { get; set; }       
        public int Drug_companyId { get; set; }        
        public decimal Drug_cost { get; set; }       
        public DateTime Drug_available_date { get; set; }        
        public DateTime Drug_Withdrawn_date { get; set; }       
        public string Drug_description { get; set; } = String.Empty;       
        public Drug_generic Drug_generic { get; set; }       
        public string Generic_equivalent_generic_id { get; set; } = String.Empty;       
        public string Other_drug_details { get; set; } = String.Empty;       
        public Prescription_Items? Prescription_Items { get; set; }       
        public DateTime DateCreated { get; set; }       
        public DateTime DateModified { get; set; }
        public string Namecompany { get; set; } = string.Empty;
    }
}

ENB.PharmaciesAndPrescriptions.MVC/Controllers/DrugMedicationController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using ENB.PharmaciesAndPrescriptions.Entities;
using ENB.PharmaciesAndPrescriptions.Entities.Repositories;
using ENB.PharmaciesAndPrescriptions.Infrastructure;
using ENB.PharmaciesAndPrescriptions.MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace ENB.PharmaciesAndPrescriptions.MVC.Controllers
{
    public class DrugMedicationController : Controller
    {       
        private readonly IAsyncDrugCompanyRepository _asyncDrugCompanyRepository;
        private readonly IAsyncUnitOfWorkFactory _asyncUnitOfWorkFactory;
        private readonly ILogger<DrugMedicationController> _logger;
        private readonly IMapper _mapper;
        private readonly INotyfService _notyf;


        public DrugMedicationController(IAsyncDrugCompanyRepository asyncDrugCompanyRepository,
                           IAsyncUnitOfWorkFactory asyncUnitOfWorkFactory, 
                           ILogger<DrugMedicationController> logger, 
                           IMapper mapper,
                           INotyfService notyf)
        {
            _asyncDrugCompanyRepository = asyncDrugCompanyRepository;
            _asyncUnitOfWorkFactory = asyncUnitOfWorkFactory;
            _logger = logger;
            _mapper = mapper;
            _notyf= notyf;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> List(int Drug_companyId)
        {
            ViewBag.IdDrgcp = Drug_companyId;
            var drug_Company = await _asyncDrugCompanyRepository.FindById(Drug_companyId);

            ViewBag.Message = drug_Company.Company_name;

            return View();
        }


        public async Task<IActionResult> GetDrugs_Medication(int Drug_companyId)
        {

            var drug_Company = await _asyncDrugCompanyRepository.FindById(Drug_companyId, x => x.Drug_Medications);

            ViewBag.Message = drug_Company.Company_name;

            var Mpdata = new List<DisplayDrugAndMedication>();

            _mapper.Map(drug_Company.Drug_Medications, Mpdata);

            return Json(new { data = Mpdata });


        }

        [HttpGet]
        public async Task<IActionResult> Create(int Drug_companyId)
        {
            ViewBag.drgcpId = Drug_companyId;

            var drug_Company = await _asyncDrugCompanyRepository.FindById(Drug_companyId);

            ViewBag.Message = drug_Company.Company_name;

            return View();
        }

        // POST: LawyerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateAndEditDrugAndMedication createAndEditDrugAndMedication,
                                                  int Drug_companyId)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                try
                {
                    await using (await _asyncUnitOfWorkFactory.Create())
                    {
                        var drug_company = await _asyncDrugCompanyRepository.FindById(Drug_companyId);                       

                        Drug_medication drug_Medication = new();

                        _mapper.Map(createAndEditDrugAndMedication, drug_Medication);

                        drug_company.Drug_Medications.Add(drug_Medication);                       

                           _notyf.Success("Lawyer event Added  Successfully! ");

                        return RedirectToAction(nameof(List), new { Drug_companyId });
                    }
                }
                catch (ModelValidationException mvex)
                {
                    foreach (var error in mvex.ValidationErrors)
                    {
                        ModelState.AddModelError(error.MemberNames.FirstOrDefault() ?? "", error.ErrorMessage!);
                    }
                }
            }
            return View();
        }



        public async Task<IActionResult> Edit(int Drug_companyId, int id)
        {

            var drug_company = await _asyncDrugCompanyRepository.FindById(Drug_companyId);
            ViewBag.Message = drug_company.Company_name;
            ViewBag.DrugcpId = Drug_companyId;
            ViewBag.Id = id;

            var drug_medication = await _asyncDrugCompanyRepository.FindById(Drug_companyId, x=>x.Drug_Medications);

            if (drug_medication == null)
            {
                return NotFound();
            }

            CreateAndEditDrugAndMedication data = new CreateAndEditDrugAndMedication();



            _mapper.Map(drug_company.Drug_Medications.Single(x => x.Id == id), data);

            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CreateAndEditDrugAndMedication createAndEditDrugAndMedication, int Drug_companyId)
        {

            ViewBag.DrgcpId = Drug_companyId;
            if (ModelState.IsValid)
            {
                try
                {
                    await using (await _asyncUnitOfWorkFactory.Create())
                    {

                        var drug_company = await _asyncDrugCompanyRepository.FindById(Drug_companyId, x => x.Drug_Medications);
                        var drug_medication = await Task.FromResult(drug_company.Drug_Medications.Single(x => x.Id == createAndEditDrugAndMedication.Id));

                        _mapper.Map(createAndEditDrugAndMedication, drug_medication);

                          _notyf.Success("Drug_Medication  updated Successfully");

                        return RedirectToAction(nameof(List), new { Drug_companyId });
                    }
                }
                catch (ModelValidationException mvex)
                {
                    foreach (var error in mvex.ValidationErrors)
                    {
                        ModelState.AddModelError(error.MemberNames.FirstOrDefault() ?? "", error.ErrorMessage!);
                    }
                }
            }
            return View();
        }

        public async Task<IActionResult> Details(int Drug_companyId, int id)
        {

            var drug_company = await _asyncDrugCompanyRepository.FindById(Drug_companyId);
           
            ViewBag.DrugcpId = Drug_companyId;
            ViewBag.Id = id;

            // var bldaprt = await _asyncApartBuildingRepository.FindById(apbldid, apbl => apbl.Apartments);

            var bldaprt = from a in _asyncDrugCompanyRepository.FindAll().Where(drgcp => drgcp.Id == Drug_companyId).SelectMany(drgmd => drgmd.Drug_Medications)
                          join drgcp in _asyncDrugCompanyRepository.FindAll() on a.Drug_companyId equals drgcp.Id
                          select new DisplayDrugAndMedication
                          {
                              Id = a.Id,
                              Drug_companyId = drgcp.Id,
                              Namecompany = drgcp.Company_name,
                              Drug_name = a.Drug_name,
                              Drug_cost = a.Drug_cost,
                              Drug_generic = a.Drug_generic,
                              DateCreated = a.DateCreated,
                              DateModified = a.DateModified,
                              Drug_available_date = a.Drug_available_date,
                              Drug_Withdrawn_date=a.Drug_Withdrawn_date,
                              Drug_description=a.Drug_description,
                              Other_drug_details=a.Other_drug_details,

                          };


            if (bldaprt == null)
            {
                return NotFound();
            }
            var data = new DisplayDrugAndMedication();

            var mydrug_medication = _mapper.Map(bldaprt.Single(x => x.Id == id), data);
            ViewBag.Message = mydrug_medication.Drug_name;
            // sglevent.Color = Enum.GetName(typeof(EventStatus), Int32.Parse(sglevent.Color));
            return View(mydrug_medication);
        }


        // GET: ApartmentController/Delete/5
        public async Task<IActionResult> Delete(int Drug_companyId, int id)
        {
            var drug_company = await _asyncDrugCompanyRepository.FindById(Drug_companyId);
            ViewBag.Message = drug_company.Company_name;
            ViewBag.DrugcpId = Drug_companyId;
            ViewBag.Id = id;

            // var bldaprt = await _asyncApartBuildingRepository.FindById(apbldid, apbl => apbl.Apartments);

            var bldaprt = from a in _asyncDrugCompanyRepository.FindAll().Where(drgcp => drgcp.Id == Drug_companyId).SelectMany(drgmd => drgmd.Drug_Medications)
                          join drgcp in _asyncDrugCompanyRepository.FindAll() on a.Drug_companyId equals drgcp.Id
                          select new DisplayDrugAndMedication
                          {
                              Id = a.Id,
                              Drug_companyId = drgcp.Id,
                              Namecompany = drgcp.Company_name,
                              Drug_name = a.Drug_name,
                              Drug_cost = a.Drug_cost,
                              Drug_generic = a.Drug_generic,
                              DateCreated = a.DateCreated,
                              DateModified = a.DateModified,
                              Drug_available_date = a.Drug_available_date,
                              Drug_Withdrawn_date = a.Drug_Withdrawn_date,
                              Drug_description = a.Drug_description,
                              Other_drug_details = a.Other_drug_details,

                          };


            if (bldaprt == null)
            {
                return NotFound();
            }
            var data = new DisplayDrugAndMedication();

            var mydrug_medication = _mapper.Map(bldaprt.Single(x => x.Id == id), data);

ENB.PharmaciesAndPrescriptions.MVC/Views/DrugMedication/Create.cshtml
@model ENB.PharmaciesAndPrescriptions.MVC.Models.CreateAndEditDrugAndMedication
@using ENB.PharmaciesAndPrescriptions.Entities;

@{
    ViewData["Title"] = "Create";
}


<div class="alert alert-primary" role="alert">
    <h2><strong>Create New Drug-Medication</strong></h2>
</div>
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create" asp-route-Drug_companyId="@ViewBag.drgcpId">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Drug_name" class="control-label card-header col-md-12" style="margin-bottom:5px"></label>
                        <input asp-for="Drug_name" class="form-control" />
                        <span asp-validation-for="Drug_name" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Drug_cost" class="control-label card-header col-md-12" style="margin-bottom:5px"></label>
                        <input asp-for="Drug_cost" class="form-control" />
                        <span asp-validation-for="Drug_cost" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Drug_available_date" class="control-label card-header col-md-12" style="margin:5px 0 5px"></label>
                        <input asp-for="Drug_available_date" class="form-control" />
                        <span asp-validation-for="Drug_available_date" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Drug_Withdrawn_date" class="control-label card-header col-md-12" style="margin:5px 0 5px"></label>
                        <input asp-for="Drug_Withdrawn_date" class="form-control" />
                        <span asp-validation-for="Drug_Withdrawn_date" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
               
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Drug_generic" class="control-label card-header col-md-12" style="margin:5px 0 5px"></label>
                        <select asp-for="Drug_generic" class="form-control" asp-items="Html.GetEnumSelectList<Drug_generic>()"></select>
                        <span asp-validation-for="Drug_generic" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Generic_equivalent_generic_id" class="control-label card-header col-md-12" style="margin:5px 0 5px"></label>
                        <input asp-for="Generic_equivalent_generic_id" class="form-control" />
                        <span asp-validation-for="Generic_equivalent_generic_id" class="text-danger"></span>
                    </div>
                </div>
                 <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Drug_description" class="control-label card-header col-md-12" style="margin:5px 0 10px"></label>
                        <textarea asp-for="Drug_description" type="text" class="form-control" rows="5" autofocus></textarea>
                        <span asp-validation-for="Drug_description" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Other_drug_details" class="control-label card-header col-md-12" style="margin:5px 0 10px"></label>
                        <textarea asp-for="Other_drug_details" type="text" class="form-control" rows="5" autofocus></textarea>
                        <span asp-validation-for="Other_drug_details" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-top:25px">
                <div class="col-md-6">
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <a asp-action="List" asp-route-Drug_companyId="@ViewBag.IdDrgcp" class="btn btn-secondary btn-block col-md-4">Back to List</a>
                    </div>
                </div>
             </div>
        </form>
    </div>
</div>

ENB.PharmaciesAndPrescriptions.MVC/Views/DrugMedication/Delete.cshtml
@using ENB.PharmaciesAndPrescriptions.Entities;
@model ENB.PharmaciesAndPrescriptions.MVC.Models.DisplayDrugAndMedication;

@{
    ViewData["Title"] = "Delete";
}


<div class="alert alert-danger" role="alert">
    <h2><strong>Do you really want to remove Drug: @ViewBag.Id ?</strong></h2>
</div>

<div id="view-all">
    @await Html.PartialAsync("_Details", Model)
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <a asp-action="List" asp-route-Drug_companyId="@ViewBag.DrugcpId" class="btn btn-secondary btn-block col-md-4">Back to List</a>
            </div>
        </div>
    </div>
}

ENB.PharmaciesAndPrescriptions.MVC/Views/DrugMedication/Details.cshtml
@using ENB.PharmaciesAndPrescriptions.Entities;
@model ENB.PharmaciesAndPrescriptions.MVC.Models.DisplayDrugAndMedication;

@{
    ViewData["Title"] = "Details";
}

<div class="alert alert-primary" role="alert">
    <h2><strong>Details Drug: @ViewBag.Message</strong></h2>
</div>

<div id="view-all">
    @await Html.PartialAsync("_Details", Model)
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }
    <div class="row">
        <div class="col-md-6">
        <a asp-action="Edit" asp-controller="DrugMedication" asp-route-id="@ViewBag.Id" class="btn btn-info btn-block col-md-2">Edit</a>
        </div>
        <div class="col-md-6">
        <a asp-action="List" asp-route-Drug_companyId="@ViewBag.DrugcpId" class="btn btn-secondary btn-block col-md-5">Back to List</a>
        </div>
    </div>
    

ENB.PharmaciesAndPrescriptions.MVC/Views/DrugMedication/Edit.cshtml
@model ENB.PharmaciesAndPrescriptions.MVC.Models.CreateAndEditDrugAndMedication
@using ENB.PharmaciesAndPrescriptions.Entities;

@{
    ViewData["Title"] = "Edit";
}


<div class="alert alert-primary" role="alert">
    <h2><strong>Create New Drug-Medication</strong></h2>
</div>
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit" asp-route-id="@ViewBag.Id" asp-route-Drug_companyId="@ViewBag.DrugcpId">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Drug_name" class="control-label card-header col-md-12" style="margin-bottom:5px"></label>
                        <input asp-for="Drug_name" class="form-control" />
                        <span asp-validation-for="Drug_name" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Drug_cost" class="control-label card-header col-md-12" style="margin-bottom:5px"></label>
                        <input asp-for="Drug_cost" class="form-control" />
                        <span asp-validation-for="Drug_cost" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Drug_available_date" class="control-label card-header col-md-12" style="margin:5px 0 5px"></label>
                        <input asp-for="Drug_available_date" class="form-control" />
                        <span asp-validation-for="Drug_available_date" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Drug_Withdrawn_date" class="control-label card-header col-md-12" style="margin:5px 0 5px"></label>
                        <input asp-for="Drug_Withdrawn_date" class="form-control" />
                        <span asp-validation-for="Drug_Withdrawn_date" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">

                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Drug_generic" class="control-label card-header col-md-12" style="margin:5px 0 5px"></label>
                        <select asp-for="Drug_generic" class="form-control" asp-items="Html.GetEnumSelectList<Drug_generic>()"></select>
                        <span asp-validation-for="Drug_generic" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Generic_equivalent_generic_id" class="control-label card-header col-md-12" style="margin:5px 0 5px"></label>
                        <input asp-for="Generic_equivalent_generic_id" class="form-control" />
                        <span asp-validation-for="Generic_equivalent_generic_id" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Drug_description" class="control-label card-header col-md-12" style="margin:5px 0 10px"></label>
                        <textarea asp-for="Drug_description" type="text" class="form-control" rows="5" autofocus></textarea>
                        <span asp-validation-for="Drug_description" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Other_drug_details" class="control-label card-header col-md-12" style="margin:5px 0 10px"></label>
                        <textarea asp-for="Other_drug_details" type="text" class="form-control" rows="5" autofocus></textarea>
                        <span asp-validation-for="Other_drug_details" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-top:25px">
                <div class="col-md-6">
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <a asp-action="List" asp-route-Drug_companyId="@ViewBag.IdDrgcp" class="btn btn-secondary btn-block col-md-4">Back to List</a>
                    </div>
                </div>
        </form>
    </div>
</div>

ENB.PharmaciesAndPrescriptions.MVC/Views/DrugMedication/List.cshtml
@using ENB.PharmaciesAndPrescriptions.Entities;
@model IEnumerable<ENB.PharmaciesAndPrescriptions.MVC.Models.DisplayDrugAndMedication>
@{
    ViewData["Title"] = "List";

}

<div class="alert alert-primary" role="alert">
    <h2><strong>Drug Company : @ViewBag.Message </strong></h2>
</div>
<a asp-action="Create" id="adddrug_medication" asp-controller="DrugMedication" asp-route-Drug_companyId="@ViewBag.IdDrgcp" class="btn btn-success text-white" style="margin-bottom:10px"><i class="fas fa-pills"></i> New Drug</a>
<table id="DrugMedicationTable" class="table table-striped table-bordered" width="100%">
    <thead>
        <tr>
            <th>Id</th>
            <th>DrugName</th>
            <th>Generic</th>
            <th>DrugCost</th>
            <th>Available</th>
            <th>Withdrawn#</th>
            <th> </th>
        </tr>
    </thead>
</table>

<link href="~/lib/datatable/datatables-1.12.1/css/datatables.bootstrap5.min.css" rel="stylesheet" />

@section scripts{
    <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="~/lib/datatable/datatables-1.12.1/js/jquery.datatables.min.js"></script>
    <script src="~/lib/datatable/datatables-1.12.1/js/datatables.bootstrap5.min.js"></script>
    <script>
        var Popup, datatable, IdDrgcp = parseInt('@ViewBag.IdDrgcp'), IdWard = parseInt('@ViewBag.Ward_Id')
        $(document).ready(function () {
            datatable = $("#DrugMedicationTable").DataTable({
                "ajax": {
                    "url": "/DrugMedication/GetDrugs_Medication/?Drug_companyId=" + IdDrgcp + "",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [

                    { "data": "id" },
                    {
                        "data": "drug_name",
                        "width": "50px",
                        "render": function (data, type, row, meta) {
                            return '<b><a href="/DrugMedication/Details/?id=' + row.id + "&Drug_companyId=" + IdDrgcp + '">' + data + '</b></a>';
                        }
                    },
                    {
                        "data": "drug_generic",
                        "render": RefGeneric

                    },
                    { "data": "drug_cost" },
                    { "data": "drug_available_date", "render": dateFormatter },
                    { "data": "drug_Withdrawn_date", "render": dateFormatter },
                    {
                        "data": "id", "render": function (data) {
                            return "<a class= 'btn btn-primary btn-sm text-white' onclick=location.href='@Url.Action("Edit","DrugMedication")?id=" + data + "&Drug_companyId=" + IdDrgcp + "'><i class='fas fa-pencil'></i><b> Edit</b></a>" + "\r\n" +
                                "<a class= 'btn btn-danger btn-sm text-white' style = 'margin-left:5px' onclick =location.href='@Url.Action("Delete","DrugMedication")?id=" + data + "&Drug_companyId=" + IdDrgcp + "'> <i class='fa-solid fa-trash-can' > </i><b> Delete</b > </a> " + "\r\n" +
                                "<a class= 'btn btn-info btn-sm' style='margin-left:5px' onclick=location.href='@Url.Action("List", "ApartmentBooking")?ApartmentId=" + data + "&Apartment_BuildingId=" + IdDrgcp + "'><i class='far fa-building'></i><b> Booking</b> </a>" + "\r\n" +
                                "<a class= 'btn btn-info btn-sm' style='margin-left:5px' onclick=location.href='@Url.Action("List", "ApartmentFacility")?ApartmentId=" + data + "&Apartment_BuildingId=" + IdDrgcp + "'><i class='far fa-building'></i><b> Facilities</b> </a>";
                        },
                        "orderable": false,
                        "searchable": false,
                        "width": "350px"
                    }

                ],
                "language": {

                    "emptyTable": "No data Found, Please Click On <b>Add New</b> Button"
                }

            });

        });




        console.log(IdDrgcp);


        function dateFormatter(data) {
            var dateAsString = data;

            var yearNumber = dateAsString.substring(0, 4);
            var monthNumber = dateAsString.substring(5, 7);
            var dayNumber = dateAsString.substring(8, 10);
            var dat = dayNumber + "/" + monthNumber + "/" + yearNumber;
            return dat;
        }

        function RefGeneric(data) {
            var typgen;
            switch (data) {
                case 1:
                    typgen = "Yes"
                    break;
                case 2:
                    typgen = "No"
                    break;                
                default:
                // code block
            }
            return typgen
        }

    </script>
    }