ENB.PharmaciesAndPrescriptions.MVC/Models/Physician/CreateAndEditPhysician.cs
using ENB.PharmaciesAndPrescriptions.Entities;
using ENB.PharmaciesAndPrescriptions.Entities.Collections;
using ENB.PharmaciesAndPrescriptions.MVC.Models;
using System.ComponentModel.DataAnnotations;

namespace ENB.PharmaciesAndPrescriptions.MVC.Models
{
    public class CreateAndEditPhysician: IValidatableObject
    {
        #region "Public Properties"

        public int Id { get; set; }
        public string FirstName { get; set; } = string.Empty;


        public string LastName { get; set; } = string.Empty;

        public string EmailAddress { get; set; } = string.Empty;

        public Gender Gender { get; set; }
        public string PhoneNumber { get; set; } = string.Empty;

        public DateTime DateOfBirth
        {
            get;
            set;
        }

        

        public string Other_details { get; set; } = string.Empty;   
       

        public Prescriptions? Prescriptions { get; set; }
        #endregion

        #region validation
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (Gender==Gender.None)
            {
                yield return new ValidationResult("Gender can't be None.", new[] { "Gender" });
            }
            if (String.IsNullOrEmpty(PhoneNumber))
            {
                yield return new ValidationResult("PhoneNumber can't be None.", new[] { "PhoneNumber" });
            }

            if (String.IsNullOrEmpty(EmailAddress))
            {
                yield return new ValidationResult("EmailAddress can't be None.", new[] { "EmailAddress" });
            }
        }
        #endregion
    }
}

ENB.PharmaciesAndPrescriptions.MVC/Models/Physician/DisplayPhysician.cs
using ENB.PharmaciesAndPrescriptions.Entities;
using ENB.PharmaciesAndPrescriptions.Entities.Collections;
using ENB.PharmaciesAndPrescriptions.MVC.Models;
using System.ComponentModel.DataAnnotations;

namespace ENB.PharmaciesAndPrescriptions.MVC.Models
{
    public class DisplayPhysician
    {
        #region "Public Properties"

        public int Id { get; set; }
        public string FirstName { get; set; }=string.Empty;

       
        public string LastName { get; set; }=string.Empty;

        public string EmailAddress { get; set; } = String.Empty;

        public Gender Gender { get; set; }
        public string PhoneNumber { get; set; } = String.Empty;


        [Display(Name = "Date of birth")]
        [DisplayFormat(DataFormatString = "{0: MM/dd/yyyy}")]
        public DateTime DateOfBirth
        {
            get;
            set;
        }
       
        
        public string FullName { get; set; }=string.Empty;

        public Prescriptions? Prescriptions { get; set; }

        public string Other_details { get; set; } = string.Empty;
        #endregion

    }
}

ENB.PharmaciesAndPrescriptions.MVC/Controllers/CustomerController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using ENB.PharmaciesAndPrescriptions.Entities;
using ENB.PharmaciesAndPrescriptions.Entities.Repositories;
using ENB.PharmaciesAndPrescriptions.Infrastructure;
using ENB.PharmaciesAndPrescriptions.MVC.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ENB.PharmaciesAndPrescriptions.MVC.Controllers
{
    public class CustomerController : Controller
    {
        private readonly IMapper _mapper;
        private readonly ILogger<CustomerController> _logger;
        private readonly IAsyncCustomerRepository _asyncCustomerRepository;
        private readonly IAsyncUnitOfWorkFactory _asyncUnitOfWorkFactory;
        private readonly INotyfService _notyf;
        public CustomerController( IMapper mapper, ILogger<CustomerController> logger,
                                   IAsyncCustomerRepository asyncCustomerRepository, 
                                   IAsyncUnitOfWorkFactory asyncUnitOfWorkFactory,
                                   INotyfService notyf)
        {
            _mapper = mapper;
            _logger = logger;   
            _asyncCustomerRepository = asyncCustomerRepository;
            _asyncUnitOfWorkFactory= asyncUnitOfWorkFactory;
            _notyf = notyf;
        }

        // GET: CustomerController
        public ActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetCustomerData()
        {
            IQueryable<Customer> allcustomer = _asyncCustomerRepository.FindAll();

            var Mpdata = _mapper.Map<List<DisplayCustomer>>(allcustomer).ToList();
            await Task.FromResult(Mpdata);
            return Json(new { data = Mpdata });
        }

        // GET: CustomerController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            ViewBag.Id = id;

            _logger.LogError($"Id :{id} of Customer not found");

            Customer dbCustomer = await _asyncCustomerRepository.FindById(id);

            ViewBag.Message = dbCustomer.FullName;

            _logger.LogInformation($"Details of Customer: {ViewBag.Message}");

            if (dbCustomer == null)
            {
                return NotFound();
            }

            var data = _mapper.Map<DisplayCustomer>(dbCustomer);

            return View(data);
        }

        // GET: CustomerController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CustomerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]        
        public async Task<IActionResult> Create(CreateAndEditCustomer createAndEditCustomer )
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                try
                {
                    await using (await _asyncUnitOfWorkFactory.Create())
                    {
                        
                        Customer dbCustomer = new(); 

                        _mapper.Map(createAndEditCustomer, dbCustomer);
                        await _asyncCustomerRepository.Add(dbCustomer);

                        _notyf.Success("Customer Created  Successfully! ");

                        return RedirectToAction("Index");
                    }
                }
                catch (ModelValidationException mvex)
                {
                    foreach (var error in mvex.ValidationErrors)
                    {
                        ModelState.AddModelError(error.MemberNames.FirstOrDefault() ?? "", error.ErrorMessage!);
                    }
                }
            }
            return View();
        }

        // GET: CustomerController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {

            _logger.LogError($"Customer {id} not found");
           
            Customer dbCustomer = await _asyncCustomerRepository.FindById(id);

            if (dbCustomer==null)
            {
                return NotFound();
            }
            var data = await Task.FromResult(_mapper.Map<CreateAndEditCustomer>(dbCustomer));

            return View(data);
        }

        // POST: CustomerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CreateAndEditCustomer createAndEditCustomer)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await using (await _asyncUnitOfWorkFactory.Create())
                    {

                        Customer dbCustomerToUpdate = await _asyncCustomerRepository.FindById(createAndEditCustomer.Id);

                        _mapper.Map(createAndEditCustomer, dbCustomerToUpdate, typeof(CreateAndEditCustomer), typeof(Customer));

                         _notyf.Success("Customer Update  Successfully! ");

                        return RedirectToAction(nameof(Index));
                    }
                }
                catch (ModelValidationException mvex)
                {
                    foreach (var error in mvex.ValidationErrors)
                    {
                        ModelState.AddModelError(error.MemberNames.FirstOrDefault() ?? "", error.ErrorMessage!);
                    }
                }
            }
            return View();
        }

        // GET: CustomerController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            Customer dbCustomer = await _asyncCustomerRepository.FindById(id);
            ViewBag.Message = dbCustomer.FullName;

            if (dbCustomer == null)
            {
                return NotFound();
            }
            var data = _mapper.Map<DisplayCustomer>(dbCustomer);
            return View(data);
        }

        // POST: CustomerController/Delete/5
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Customer dbCustomer = await _asyncCustomerRepository.FindById(id);
         await using (await _asyncUnitOfWorkFactory.Create())
            {
                 _asyncCustomerRepository.Remove(dbCustomer);

                  _notyf.Error("Customer Removed  Successfully! ");
            }

            return RedirectToAction(nameof(Index)); ;
        }
    }
}

ENB.PharmaciesAndPrescriptions.MVC/Controllers/PhysicianController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using ENB.PharmaciesAndPrescriptions.Entities.Repositories;
using ENB.PharmaciesAndPrescriptions.Entities;
using ENB.PharmaciesAndPrescriptions.Infrastructure;
using ENB.PharmaciesAndPrescriptions.MVC.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ENB.PharmaciesAndPrescriptions.MVC.Controllers
{
    public class PhysicianController : Controller
    {
        private readonly IMapper _mapper;
        private readonly ILogger<PhysicianController> _logger;
        private readonly IAsyncPhysicianRepository _asyncPhysicianRepository;
        private readonly IAsyncUnitOfWorkFactory _asyncUnitOfWorkFactory;
        private readonly INotyfService _notyf;
        public PhysicianController(IMapper mapper, ILogger<PhysicianController> logger,
                                   IAsyncPhysicianRepository asyncPhysicianRepository,
                                   IAsyncUnitOfWorkFactory asyncUnitOfWorkFactory,
                                   INotyfService notyf)
        {
            _mapper = mapper;
            _logger = logger;
            _asyncPhysicianRepository = asyncPhysicianRepository;
            _asyncUnitOfWorkFactory = asyncUnitOfWorkFactory;
            _notyf = notyf;
        }

        // GET: CustomerController
        public ActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetPhysicianData()
        {
            IQueryable<Physician> allPhysician = _asyncPhysicianRepository.FindAll();

            var Mpdata = _mapper.Map<List<DisplayPhysician>>(allPhysician).ToList();
            await Task.FromResult(Mpdata);
            return Json(new { data = Mpdata });
        }

        // GET: CustomerController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            ViewBag.Id = id;

            _logger.LogError($"Id :{id} of Customer not found");

            Physician dbPhysician = await _asyncPhysicianRepository.FindById(id);

            ViewBag.Message = dbPhysician.FullName;

            _logger.LogInformation($"Details of Physician: {ViewBag.Message}");

            if (dbPhysician == null)
            {
                return NotFound();
            }

            var data = _mapper.Map<DisplayPhysician>(dbPhysician);

            return View(data);
        }

        // GET: CustomerController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CustomerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateAndEditPhysician createAndEditPhysician)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                try
                {
                    await using (await _asyncUnitOfWorkFactory.Create())
                    {

                        Physician dbPhysician = new();

                        _mapper.Map(createAndEditPhysician, dbPhysician);
                        await _asyncPhysicianRepository.Add(dbPhysician);

                        _notyf.Success("Physician Created  Successfully! ");

                        return RedirectToAction("Index");
                    }
                }
                catch (ModelValidationException mvex)
                {
                    foreach (var error in mvex.ValidationErrors)
                    {
                        ModelState.AddModelError(error.MemberNames.FirstOrDefault() ?? "", error.ErrorMessage!);
                    }
                }
            }
            return View();
        }

        // GET: CustomerController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {

           

            Physician dbPhysician = await _asyncPhysicianRepository.FindById(id);

            if (dbPhysician == null)
            {
               _logger.LogError($"Physician {id} not found");
                return NotFound();
            }
            var data = await Task.FromResult(_mapper.Map<CreateAndEditPhysician>(dbPhysician));

            return View(data);
        }

        // POST: CustomerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CreateAndEditPhysician createAndEditPhysician)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await using (await _asyncUnitOfWorkFactory.Create())
                    {

                        Physician dbPhysicianToUpdate = await _asyncPhysicianRepository.FindById(createAndEditPhysician.Id);

                        _mapper.Map(createAndEditPhysician, dbPhysicianToUpdate, typeof(CreateAndEditPhysician), typeof(Physician));

                        _notyf.Success("Physician Updated  Successfully! ");

                        return RedirectToAction(nameof(Index));
                    }
                }
                catch (ModelValidationException mvex)
                {
                    foreach (var error in mvex.ValidationErrors)
                    {
                        ModelState.AddModelError(error.MemberNames.FirstOrDefault() ?? "", error.ErrorMessage!);
                    }
                }
            }
            return View();
        }

        // GET: CustomerController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            Physician dbPhysician = await _asyncPhysicianRepository.FindById(id);
            ViewBag.Message = dbPhysician.FullName;

            if (dbPhysician == null)
            {
                return NotFound();
            }
            var data = _mapper.Map<DisplayPhysician>(dbPhysician);
            return View(data);
        }

        // POST: CustomerController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Physician dbPhysician = await _asyncPhysicianRepository.FindById(id);
            await using (await _asyncUnitOfWorkFactory.Create())
            {
                _asyncPhysicianRepository.Remove(dbPhysician);

                _notyf.Error("Customer Removed  Successfully! ");
            }

            return RedirectToAction(nameof(Index)); ;
        }
    }
}

ENB.PharmaciesAndPrescriptions.MVC/Views/Physician/Create.cshtml
@model ENB.PharmaciesAndPrescriptions.MVC.Models.CreateAndEditPhysician
@using ENB.PharmaciesAndPrescriptions.Entities

@{
    ViewData["Title"] = "Create";
}

<div class="alert alert-primary" role="alert">
    <h2><strong>Create New Physician</strong></h2>
</div>
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                         <div class="card-header">
                        <label asp-for="FirstName" class="control-label"></label>
                        </div>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                         <div class="card-header">
                        <label asp-for="LastName" class="control-label"></label>
                        </div>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="card-header" style="margin-top:10px">
                        <label asp-for="EmailAddress" class="control-label"></label>
                        </div>
                        <input asp-for="EmailAddress" class="form-control" />
                        <span asp-validation-for="EmailAddress" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="card-header" style="margin-top:10px">
                        <label asp-for="Gender" class="control-label"></label>
                        </div>
                        <select asp-for="Gender" class="form-control" asp-items="Html.GetEnumSelectList<Gender>()"></select>
                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="card-header" style="margin-top:10px">
                        <label asp-for="PhoneNumber" class="control-label"></label>
                        </div>
                        <input asp-for="PhoneNumber" class="form-control" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="card-header" style="margin-top:10px">
                        <label asp-for="DateOfBirth" class="control-label"></label>
                        </div>
                        <input asp-for="DateOfBirth" class="form-control" />
                        <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">                
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="card-header" style="margin-top:10px">
                        <label asp-for="Other_details" class="control-label"></label>
                        </div>
                        <textarea asp-for="Other_details" type="text" class="form-control" rows="5" autofocus></textarea>
                        <span asp-validation-for="Other_details" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-top:10px">
                <div class="col-md-6">
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <a asp-action="Index" class="btn btn-secondary btn-block col-md-4">Back to List</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

ENB.PharmaciesAndPrescriptions.MVC/Views/Physician/Delete.cshtml
@using ENB.PharmaciesAndPrescriptions.Entities;
@model ENB.PharmaciesAndPrescriptions.MVC.Models.DisplayPhysician;

@{
    ViewData["Title"] = "Delete";
}


<div class="alert alert-danger" role="alert">
    <h2><strong>Do you really want to remove: @ViewBag.Message ?</strong></h2>
</div>

<div id="view-all">
    @await Html.PartialAsync("_Details", Model)
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <a asp-action="Index" class="btn btn-secondary btn-block col-md-4">Back to List</a>
            </div>
        </div>
    </div>
}

ENB.PharmaciesAndPrescriptions.MVC/Views/Physician/Details.cshtml
@using ENB.PharmaciesAndPrescriptions.Entities;
@model ENB.PharmaciesAndPrescriptions.MVC.Models.DisplayPhysician;

@{
    ViewData["Title"] = "Details";
}

<div class="alert alert-primary" role="alert">
    <h2><strong>Details Physician: @ViewBag.Message</strong></h2>
</div>

<div id="view-all">
    @await Html.PartialAsync("_Details", Model)
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }
<div class="row">
    <div class="col-md-6">
        <a asp-action="Edit" asp-controller="Customer" asp-route-id="@ViewBag.Id" class="btn btn-info btn-block col-md-2">Edit</a>
    </div>
    <div class="col-md-6">
        <a asp-action="Index" class="btn btn-secondary btn-block col-md-5">Back to List</a>
    </div>
</div>

ENB.PharmaciesAndPrescriptions.MVC/Views/Physician/Edit.cshtml
@model ENB.PharmaciesAndPrescriptions.MVC.Models.CreateAndEditPhysician
@using ENB.PharmaciesAndPrescriptions.Entities

@{
    ViewData["Title"] = "Edit";
}

<div class="alert alert-primary" role="alert">
    <h2><strong>Edit Physician</strong></h2>
</div>
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="card-header">
                            <label asp-for="FirstName" class="control-label"></label>
                        </div>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="card-header">
                            <label asp-for="LastName" class="control-label"></label>
                        </div>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="card-header" style="margin-top:10px">
                            <label asp-for="EmailAddress" class="control-label"></label>
                        </div>
                        <input asp-for="EmailAddress" class="form-control" />
                        <span asp-validation-for="EmailAddress" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="card-header" style="margin-top:10px">
                            <label asp-for="Gender" class="control-label"></label>
                        </div>
                        <select asp-for="Gender" class="form-control" asp-items="Html.GetEnumSelectList<Gender>()"></select>
                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="card-header" style="margin-top:10px">
                            <label asp-for="PhoneNumber" class="control-label"></label>
                        </div>
                        <input asp-for="PhoneNumber" class="form-control" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="card-header" style="margin-top:10px">
                            <label asp-for="DateOfBirth" class="control-label"></label>
                        </div>
                        <input asp-for="DateOfBirth" class="form-control" />
                        <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="card-header" style="margin-top:10px">
                            <label asp-for="Other_details" class="control-label"></label>
                        </div>
                        <textarea asp-for="Other_details" type="text" class="form-control" rows="5" autofocus></textarea>
                        <span asp-validation-for="Other_details" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-top:10px">
                <div class="col-md-6">
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <a asp-action="Index" class="btn btn-secondary btn-block col-md-4">Back to List</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

ENB.PharmaciesAndPrescriptions.MVC/Views/Physician/Index.cshtml
<div class="alert alert-primary" role="alert">
    <h2><strong>List Physicians</strong></h2>
</div>

<a asp-action="Create" id="addCustomer" asp-controller="Physician" class="btn btn-success text-white" style="margin-bottom:10px"><i class="fa-solid fa-user-doctor"></i>   New Physician</a>
<table id="Physiciantable" class="table table-striped table-bordered" width="100%">
    <thead>
        <tr>
            <th>Id</th>
            <th>FullName</th>
            <th>DateOfBirth</th>
            <th>EmailAddress</th>
            <th>PhoneNumber</th>
            <th>Gender</th>
            <th> </th>
        </tr>
    </thead>
</table>

<link href="~/lib/datatable/datatables-1.12.1/css/datatables.bootstrap5.min.css" rel="stylesheet" />

@section scripts{
    <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="~/lib/datatable/datatables-1.12.1/js/jquery.datatables.min.js"></script>
    <script src="~/lib/datatable/datatables-1.12.1/js/datatables.bootstrap5.min.js"></script>
    <script>
        var Popup, datatable, IdPatient = parseInt('@ViewBag.Patient_Id'), IdWard = parseInt('@ViewBag.Ward_Id')
        $(document).ready(function () {
            datatable = $("#Physiciantable").DataTable({
                "ajax": {
                    "url": "/Physician/GetPhysicianData",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [

                    { "data": "id" },
                    {
                        "data": "fullName",
                        "width": "250px",
                        "render": function (data, type, row, meta) {
                            return '<b><a href="/Physician/Details/' + row.id + '">' + data + '</b></a>';
                        }
                    },
                    {
                        "data": "dateOfBirth",
                        "render": dateFormatter
                    },
                    { "data": "emailAddress" },
                    { "data": "phoneNumber" },
                    { "data": "gender", "render": Genderparse },
                    {
                        "data": "id", "render": function (data) {
                            return "<a class= 'btn btn-primary btn-sm text-white' onclick=location.href='@Url.Action("Edit","Physician")/" + data + "'><i class='fas fa-pencil'></i><b> Edit</b></a>" + "\r\n" +
                                "<a class= 'btn btn-danger btn-sm text-white' style = 'margin-left:5px' onclick =location.href='@Url.Action("Delete","Physician")/" + data + "' > <i class='fa-solid fa-trash-can' > </i><b> Delete</b > </a> " + "\r\n" +
                                "<a class= 'btn btn-info btn-sm' style='margin-left:5px' onclick=location.href='@Url.Action("Edit", "Addresses")?PhysicianId=" + data + "'><i class='fas fa-address-card'></i><b> Address</b> </a> " + "\r\n" +
                                "<a class= 'btn btn-info btn-sm' style='margin-left:5px' onclick=location.href='@Url.Action("ProcessAddress", "GuestAddress")?guestId=" + data + "'><i class='fa-solid fa-prescription-bottle-medical'></i><b> Prescriptions</b> </a>  ";

                        },
                        "orderable": false,
                        "searchable": false,
                        "width": "400px"
                    }

                ],
                "language": {

                    "emptyTable": "No data Found, Please Click On <b>Add New</b> Button"
                }

            });

        });







        function dateFormatter(data) {
            var dateAsString = data;

            var yearNumber = dateAsString.substring(0, 4);
            var monthNumber = dateAsString.substring(5, 7);
            var dayNumber = dateAsString.substring(8, 10);
            var dat = dayNumber + "/" + monthNumber + "/" + yearNumber;
            return dat;
        }

        function Genderparse(data) {
            var gnder;
            switch (data) {
                case 1:
                    gnder = "Male"
                    break;
                case 2:
                    gnder = "Female"
                    break;
                default:
                // code block
            }
            return gnder;
        }

    </script>
    }